CREATE TABLE KUNDE (
    KUNDENR INTEGER NOT NULL,
    NAVN VARCHAR(30) NOT NULL,
    KREDITTGRENSE DECIMAL(10,2) NOT NULL,
    POSTNR CHAR(4),
    PRIMARY KEY (KUNDENR),
    FOREIGN KEY (POSTNR) REFERENCES POSTSTED(POSTNR)
);

CREATE TABLE POSTSTED (
    POSTNR CHAR(4) NOT NULL,
    POSTSTED VARCHAR(30) NOT NULL,
    PRIMARY KEY (POSTNR)
)

CREATE TABLE BESTILLING (
    ARTNR INTEGER NOT NULL,
    KUNDENR INTEGER NOT NULL,
    KVANTIUM INTEGER NOT NULL,
    PRIMARY KEY (ARTNR, KUNDENR),
    FOREIGN KEY (ARTNR) REFERENCES ARTIKKEL(ARTNR),
    FOREIGN KEY (KUNDENR) REFERENCES KUNDE(KUNDENR)
);

CREATE TABLE ARTIKKEL (
    ARTNR INTEGER NOT NULL,
    NAVN CHAR(30) NOT NULL,
    ANT INTEGER NOT NULL,
    PRIS DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ARTNR)
);
