CREATE VIEW PROJECT_PROPERTIES (PROJECT_NAME, DEPT_NAME, NO_EMPLOYERS, HOURS_WEEK)
    AS SELECT PROJECT.PNAME, DEPARTMENT.DNAME,
              COUNT(*), SUM(HOURS)
    FROM PROJECT, DEPARTMENT, WORKS_ON
    WHERE PROJECT.DNUM = DEPARTMENT.DNUMBER
      AND PROJECT.PNUMBER = PNO
    GROUP BY PROJECT.PNAME;
